const app = new Vue({
		el: '#app',
		data: {
			characters: [
				'Mario',
				'Donkey Kong',
				'Link',
				'Samus',
				'Yoshi',
				'Kirby',
				'Fox',
				'Pikachu',
				'Luigi',
				'Ness',
				'Captain Falcon',
				'Jigglypuff',
				
				'Peach',
				'Bowser',
				'Ice Climbers',
				'Zelda & Sheik',
				'Sheik',
				'Zelda',
				'Dr. Mario',
				'Pichu',
				'Falco',
				'Marth',
				'Young Link',
				'Ganondorf',
				'Mewtwo',
				'Roy',
				'Mr. Game & Watch',
				
				'Meta Knight',
				'Pit',
				'Samus & Zero Suit',
				'Zero Suit Samus',
				'Wario',
				'Snake',
				'Ike',
				'Pokemon Trainer',
				'Squirtle',
				'Ivysaur',
				'Charizard',
				'Diddy Kong',
				'Lucas',
				'Sonic',
				'King Dedede',
				'Olimar',
				'Lucario',
				'R.O.B.',
				'Toon Link',
				'Wolf',
				
				'Villager',
				'Mega Man',
				'Wii Fit Trainer',
				'Rosalina & Luma',
				'Little Mac',
				'Greninja',
				'Mii Fighters',
				'Mii Brawler',
				'Mii Swordfighter',
				'Mii Gunner',
				'Palutena',
				'Dark Pit',
				'PAC-MAN',
				'Lucina',
				'Robin',
				'Shulk',
				'Bowser Jr.',
				'Duck Hunt',
				'Ryu',
				'Cloud',
				'Corrin',
				'Bayonetta',
				
				'Inkling',
				'Daisy',
				'Ridley',
				'Simon',
				'Richter',
				'Chrom',
				'Dark Samus',
				'King K. Rool',
				'Isabelle',
				'Ken',
				'Incineroar',
				'Piranha Plant',
				'Joker',
				'Hero',
				'Banjo & Kazooie',
				'Terry',
				'Byleth',
				'Min Min',
				'Steve',
				'Sephiroth',
				'Pyra & Mythra',
				'Pyra',
				'Mythra',
				'Kazuya',
				'Sora'
			]
		}
	});
	
const classic = ['Mario', 'Donkey Kong', 'Link', 'Samus', 'Yoshi', 'Kirby', 'Fox', 'Pikachu', 'Luigi', 'Ness', 'Captain Falcon', 'Jigglypuff'];

const melee = ['Mario', 'Donkey Kong', 'Link', 'Samus', 'Yoshi', 'Kirby', 'Fox', 'Pikachu', 'Luigi', 'Ness', 'Captain Falcon', 'Jigglypuff', 'Peach', 'Bowser', 'Ice Climbers', 'Sheik', 'Zelda', 'Dr. Mario', 'Pichu', 'Falco', 'Marth', 'Young Link', 'Ganondorf', 'Mewtwo', 'Roy', 'Mr. Game & Watch'];
				
const brawl = ['Mario', 'Donkey Kong', 'Link', 'Samus', 'Yoshi', 'Kirby', 'Fox', 'Pikachu', 'Luigi', 'Ness', 'Captain Falcon', 'Jigglypuff', 'Peach', 'Bowser', 'Ice Climbers', 'Sheik', 'Zelda', 'Falco', 'Marth', 'Ganondorf', 'Mr. Game & Watch', 'Meta Knight', 'Pit', 'Zero Suit Samus', 'Wario', 'Snake', 'Ike', 'Pokemon Trainer', 'Diddy Kong', 'Lucas', 'Sonic', 'King Dedede', 'Olimar', 'Lucario', 'R.O.B.', 'Toon Link', 'Wolf'];
				
const four = ['Mario', 'Donkey Kong', 'Link', 'Samus', 'Yoshi', 'Kirby', 'Fox', 'Pikachu', 'Luigi', 'Ness', 'Captain Falcon', 'Jigglypuff', 'Peach', 'Bowser',  'Sheik', 'Zelda', 'Dr. Mario', 'Falco', 'Marth', 'Ganondorf', 'Mewtwo', 'Roy', 'Mr. Game & Watch', 'Meta Knight', 'Pit', 'Zero Suit Samus', 'Wario', 'Ike', 'Charizard', 'Diddy Kong', 'Lucas', 'Sonic', 'King Dedede', 'Olimar', 'Lucario', 'R.O.B.', 'Toon Link', 'Villager', 'Mega Man', 'Wii Fit Trainer', 'Rosalina & Luma', 'Little Mac', 'Greninja', 'Mii Brawler', 'Mii Swordfighter', 'Mii Gunner', 'Palutena', 'Dark Pit', 'PAC-MAN', 'Lucina', 'Robin', 'Shulk', 'Bowser Jr.', 'Duck Hunt', 'Ryu', 'Cloud', 'Corrin', 'Bayonetta'];

const ultimate = ['Mario', 'Donkey Kong', 'Link', 'Samus', 'Yoshi', 'Kirby', 'Fox', 'Pikachu', 'Luigi', 'Ness', 'Captain Falcon', 'Jigglypuff', 'Peach', 'Bowser', 'Ice Climbers', 'Sheik', 'Zelda', 'Dr. Mario', 'Pichu', 'Falco', 'Marth', 'Young Link', 'Ganondorf', 'Mewtwo', 'Roy', 'Mr. Game & Watch', 'Meta Knight', 'Pit', 'Zero Suit Samus', 'Wario', 'Snake', 'Ike', 'Pokemon Trainer', 'Diddy Kong', 'Lucas', 'Sonic', 'King Dedede', 'Olimar', 'Lucario', 'R.O.B.', 'Toon Link', 'Wolf', 'Villager', 'Mega Man', 'Wii Fit Trainer', 'Rosalina & Luma', 'Little Mac', 'Greninja', 'Mii Brawler', 'Mii Swordfighter', 'Mii Gunner', 'Palutena', 'Dark Pit', 'PAC-MAN', 'Lucina', 'Robin', 'Shulk', 'Bowser Jr.', 'Duck Hunt', 'Ryu', 'Cloud', 'Corrin', 'Bayonetta', 'Inkling', 'Daisy', 'Ridley', 'Simon', 'Richter', 'Chrom', 'Dark Samus', 'King K. Rool', 'Isabelle', 'Ken', 'Incineroar', 'Piranha Plant', 'Joker', 'Hero', 'Banjo & Kazooie', 'Terry', 'Byleth', 'Min Min', 'Steve', 'Sephiroth', 'Pyra & Mythra', 'Kazuya', 'Sora'];